from pathlib import Path

# classMedia.php is historical latin-1; preserve bytes outside edited ASCII.
p = Path('include/classMedia.php')
s = p.read_text(encoding='latin-1')
old = '''        // MediaGallery 1.8: square crop at rest, complete image on hover/focus.\n        // Prefer the lighter display derivative for the full layer when it preserves\n        // the original aspect ratio. If a legacy derivative is itself cropped, use\n        // the original image so portrait media can really be revealed in full.\n        $media_card_preview = $media_item_thumbnail;\n        if ($searchmode == 0 && $this->type == 0 && $this->remote != 1 && !empty($direct_url)) {\n            $card_cover_source = !empty($this->media_thumbnail) ? $this->media_thumbnail : $direct_url;\n            $card_full_source = $direct_url;\n            $orig_preview_path = self::getFilePath('orig', $this->filename, $this->mime_ext);\n            if (file_exists($orig_preview_path)) {\n                $orig_preview_size = @getimagesize($orig_preview_path);\n                $display_preview_size = ($direct_preview_path != '') ? @getimagesize($direct_preview_path) : false;\n                if ($orig_preview_size !== false && $orig_preview_size[0] > 0 && $orig_preview_size[1] > 0) {\n                    $use_original_preview = ($display_preview_size === false\n                        || $display_preview_size[0] < 1 || $display_preview_size[1] < 1);\n                    if (!$use_original_preview) {\n                        $orig_ratio = $orig_preview_size[0] / $orig_preview_size[1];\n                        $display_ratio = $display_preview_size[0] / $display_preview_size[1];\n                        $use_original_preview = abs($orig_ratio - $display_ratio) > 0.02;\n                    }\n                    if ($use_original_preview) {\n                        $card_full_source = self::getFileUrl('orig', $this->filename, $this->mime_ext);\n                    }\n                }\n            }\n            $card_cover_url = MG_escapeHTML($card_cover_source);\n            $card_full_url = MG_escapeHTML($card_full_source);\n'''
new = '''        // MediaGallery 1.8: use the display derivative for the sharp square cover\n        // and the uncropped original for the mini-lightbox whenever it exists.\n        $media_card_preview = $media_item_thumbnail;\n        if ($searchmode == 0 && $this->type == 0 && $this->remote != 1 && !empty($direct_url)) {\n            $card_cover_source = $direct_url;\n            $card_full_source = $direct_url;\n            $orig_preview_path = self::getFilePath('orig', $this->filename, $this->mime_ext);\n            if (file_exists($orig_preview_path)) {\n                $card_full_source = self::getFileUrl('orig', $this->filename, $this->mime_ext);\n            }\n            $card_cover_url = MG_escapeHTML($card_cover_source);\n            $card_full_url = MG_escapeHTML($card_full_source);\n'''
if old not in s:
    raise SystemExit('classMedia preview source block not found')
s = s.replace(old, new, 1)
p.write_text(s, encoding='latin-1')

p = Path('include/common.php')
s = p.read_text(encoding='utf-8')
old = '''    // Keep separate cover/full sources for the mini-lightbox. A display derivative\n    // that preserves the original ratio stays preferred; a cropped legacy derivative\n    // falls back to the original so portrait covers can be revealed completely.\n    $album_full_image = $album_last_image;\n    if ($album_data['tn_attached'] != 1 && isset($display_cover_filename) && $display_cover_filename != '') {\n        list($original_cover_image, $original_cover_size) = MG_getImageUrl(\n            'orig/' . $display_cover_filename[0] . '/' . $display_cover_filename\n        );\n        if ($original_cover_size !== false && $original_cover_size[0] > 0 && $original_cover_size[1] > 0) {\n            $use_original_cover = ($mediasize === false || $mediasize[0] < 1 || $mediasize[1] < 1);\n            if (!$use_original_cover) {\n                $original_cover_ratio = $original_cover_size[0] / $original_cover_size[1];\n                $preview_cover_ratio = $mediasize[0] / $mediasize[1];\n                $use_original_cover = abs($original_cover_ratio - $preview_cover_ratio) > 0.02;\n            }\n            if ($use_original_cover) {\n                $album_full_image = $original_cover_image;\n            }\n        }\n    }\n'''
new = '''    // Keep the display derivative for the square card, but always use the\n    // uncropped original in the mini-lightbox when that source is available.\n    $album_full_image = $album_last_image;\n    if ($album_data['tn_attached'] != 1 && isset($display_cover_filename) && $display_cover_filename != '') {\n        list($original_cover_image, $original_cover_size) = MG_getImageUrl(\n            'orig/' . $display_cover_filename[0] . '/' . $display_cover_filename\n        );\n        if ($original_cover_size !== false && $original_cover_size[0] > 0 && $original_cover_size[1] > 0) {\n            $album_full_image = $original_cover_image;\n        }\n    }\n'''
if old not in s:
    raise SystemExit('common album full source block not found')
s = s.replace(old, new, 1)
p.write_text(s, encoding='utf-8')
