from pathlib import Path

path = Path('functions_legacy.inc')
text = path.read_text(encoding='latin-1')

old = '''function plugin_getheadercode_mediagallery()\n{\n    global $_CONF, $_MG_CONF, $_SCRIPTS, $mgLightBox, $swfjsinclude;\n\n    $retval = '';\n\n    //\n    // Check to see if the template path is using the plugins/ directory, if yes,\n    // we must point to the stylesheet in public_html/mediagallery/\n    //\n    if ($_MG_CONF['template_path'] == $_CONF['path'] . 'plugins/mediagallery/templates') {\n        $styleFile = $_MG_CONF['site_url'] . '/style.css';\n    } else {\n        $styleFile = $_CONF['layout_url'] . '/mediagallery/style.css';\n    }\n    $retval .= LB . '<link rel="stylesheet" type="text/css" href="' . $styleFile . '"' . XHTML . '>' . LB;\n\n    $_SCRIPTS->setJavaScriptFile('mediagallery', '/mediagallery/js/mediagallery.js');\n\n    $_SCRIPTS->setJavaScriptLibrary('jquery');\n\n    if (! $_MG_CONF['disable_lightbox']) {\n        $_SCRIPTS->setJavaScriptFile('jquery.slimbox2', '/mediagallery/js/slimbox2.js');\n    }\n\n    $_SCRIPTS->setJavaScriptFile('jquery.cyclelite', '/mediagallery/js/jquery.cycle.lite.min.js');\n\n\n    $_SCRIPTS->setCSSFile('mg.framecss' . $_MG_CONF['random_skin'] , '/mediagallery/frames/' . $_MG_CONF['random_skin'] . '/style.css', false);\n\n    return $retval;\n}\n'''

new = '''function plugin_getheadercode_mediagallery()\n{\n    global $_CONF, $_MG_CONF, $_SCRIPTS, $mgLightBox, $swfjsinclude;\n\n    $retval = '';\n    $assetVersion = !empty($_MG_CONF['pi_version']) ? $_MG_CONF['pi_version'] : '1.8.0';\n\n    //\n    // Check to see if the template path is using the plugins/ directory, if yes,\n    // we must point to the stylesheet in public_html/mediagallery/.\n    // Append the plugin version and file modification time so browsers keep\n    // caching unchanged CSS while immediately seeing each updated stylesheet.\n    //\n    if ($_MG_CONF['template_path'] == $_CONF['path'] . 'plugins/mediagallery/templates') {\n        $stylePath = $_CONF['path_html'] . 'mediagallery/style.css';\n        $styleFile = $_MG_CONF['site_url'] . '/style.css';\n    } else {\n        $stylePath = $_CONF['path_layout'] . 'mediagallery/style.css';\n        $styleFile = $_CONF['layout_url'] . '/mediagallery/style.css';\n    }\n\n    $styleMtime = @filemtime($stylePath);\n    $styleCacheVersion = $assetVersion;\n    if ($styleMtime !== false) {\n        $styleCacheVersion .= '-' . $styleMtime;\n    }\n    $styleFile .= '?v=' . rawurlencode($styleCacheVersion);\n    $retval .= LB . '<link rel="stylesheet" type="text/css" href="' . $styleFile . '"' . XHTML . '>' . LB;\n\n    $_SCRIPTS->setJavaScriptFile('mediagallery', '/mediagallery/js/mediagallery.js');\n\n    $_SCRIPTS->setJavaScriptLibrary('jquery');\n\n    if (! $_MG_CONF['disable_lightbox']) {\n        $_SCRIPTS->setJavaScriptFile('jquery.slimbox2', '/mediagallery/js/slimbox2.js');\n    }\n\n    $_SCRIPTS->setJavaScriptFile('jquery.cyclelite', '/mediagallery/js/jquery.cycle.lite.min.js');\n\n    $frameStyleRelative = '/mediagallery/frames/' . $_MG_CONF['random_skin'] . '/style.css';\n    $frameStylePath = $_CONF['path_html'] . ltrim($frameStyleRelative, '/');\n    $frameMtime = @filemtime($frameStylePath);\n    $frameCacheVersion = $assetVersion;\n    if ($frameMtime !== false) {\n        $frameCacheVersion .= '-' . $frameMtime;\n    }\n    $_SCRIPTS->setCSSFile(\n        'mg.framecss' . $_MG_CONF['random_skin'],\n        $frameStyleRelative . '?v=' . rawurlencode($frameCacheVersion),\n        false\n    );\n\n    return $retval;\n}\n'''

if text.count(old) != 1:
    raise SystemExit('Expected exactly one plugin_getheadercode_mediagallery() block')

path.write_text(text.replace(old, new), encoding='latin-1')
print('Updated MediaGallery CSS cache versioning')
